### ISSUE TITLE
992px width breaks the sidebar

### ISSUE THREAD

**Issue by KatyPurry** [ColorlibHQ/Sparkling#267]
Hey,
If you set the width at 992px, it breaks the sidebar and pulls it after the main content : 
Demo : https://colorlibhub.com/sparkling/

![image](https://user-images.githubusercontent.com/89610869/176571963-e0bf0e48-6f30-46a5-b779-8bbfd39f2b8b.png)

**Comment by puikinsh** [comment]
Confirmed, and a fix is up in #274.

The cause is an off-by-one in three media queries. Bootstrap 3's `md` grid starts at `min-width: 992px`, but the theme had:

```css
/* bootstrap.css  */ @media (min-width: 992px) { .col-md-8 { float: left } }   /* 0,1,0 */
/* style.css:2496 */ @media (max-width: 992px) { .side-pull-left .main-content-inner
                                                 { float: none } }             /* 0,2,0 */
```

At **exactly** 992px both rules match. The theme's selector is more specific and loads later, so it wins: the content unfloats while still 66.67% wide, and the sidebar can no longer sit beside it and drops underneath. That's the layout in your screenshot.

The same overlap existed at 768px, where `.pull-left`/`.pull-right` were forced to `float: none !important` and `.flex-caption` was hidden, while Bootstrap's `sm` grid was already side-by-side. Since 768px is iPad portrait, that one was hitting a very common device exactly.

Boundaries are now 767/768 and 991/992, with the paired `min-width: 769px` moved to 768px so closing the overlap doesn't open a gap. Landing in **2.6.4**.

Thanks for the precise report — the exact-width detail is what made it findable.
